In [1]:
import numpy as np
import pandas as pd

In [2]:
# Creating Numpy Array
a = np.array([4,5,6,7,8,9])
a

array([4, 5, 6, 7, 8, 9])

In [3]:
print(a)

[4 5 6 7 8 9]


In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(6,)

In [6]:
a.dtype

dtype('int32')

In [7]:
a.size

6

In [8]:
len(a)

6

In [9]:
# accessing array
a[0]

4

In [10]:
a[:3]

array([4, 5, 6])

In [11]:
a = np.array([[4,8,3,11],[2,9,6,12],[1,2,7,13]])
a

array([[ 4,  8,  3, 11],
       [ 2,  9,  6, 12],
       [ 1,  2,  7, 13]])

In [12]:
a.shape

(3, 4)

In [13]:
a[1,1:3]

array([9, 6])

In [14]:
a[:2,3]

array([11, 12])

In [15]:
b = np.array([[[4,41],[8,81],[3,31],[11,111]],[[2,21],[9,91],[6,61],[12,121]],[[1,11],[2,21],[7,71],[13,131]]])
b

array([[[  4,  41],
        [  8,  81],
        [  3,  31],
        [ 11, 111]],

       [[  2,  21],
        [  9,  91],
        [  6,  61],
        [ 12, 121]],

       [[  1,  11],
        [  2,  21],
        [  7,  71],
        [ 13, 131]]])

In [16]:
b.shape

(3, 4, 2)

In [17]:
b[1:,3,:]

array([[ 12, 121],
       [ 13, 131]])

In [18]:
b[:2,:2,0]

array([[4, 8],
       [2, 9]])

In [19]:
a[0]

array([ 4,  8,  3, 11])

In [22]:
a[0,0] = 34

In [23]:
a

array([[34,  8,  3, 11],
       [ 2,  9,  6, 12],
       [ 1,  2,  7, 13]])

In [24]:
a.sum()

108

In [25]:
a.sum(axis=0)

array([37, 19, 16, 36])

In [26]:
a.sum(axis=1)

array([56, 29, 23])

In [27]:
a.mean()

9.0

In [28]:
a.max()

34

In [29]:
a.min()

1

In [30]:
# Functions to Create Array

In [31]:
a1 = np.linspace(1,100,5) # number of values i.e. 5
a1

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [32]:
a2 = np.arange(1,100,5) # the gap, i.e. 5
a2

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.zeros(3)

array([0., 0., 0.])

In [36]:
np.random.rand(3)

array([0.04940711, 0.74262286, 0.17855763])

In [37]:
np.random.randint(1,100,3)

array([70, 24, 42])

In [38]:
a

array([[34,  8,  3, 11],
       [ 2,  9,  6, 12],
       [ 1,  2,  7, 13]])

In [39]:
a.reshape(6,2)

array([[34,  8],
       [ 3, 11],
       [ 2,  9],
       [ 6, 12],
       [ 1,  2],
       [ 7, 13]])

In [41]:
np.hsplit(a,2)

[array([[34,  8],
        [ 2,  9],
        [ 1,  2]]),
 array([[ 3, 11],
        [ 6, 12],
        [ 7, 13]])]

# Pandas

1. Series (Single Column Data) (1D)
2. DataFrame (Multi-column / Tabular) (2D)
3. Panel (Multi-table) (3D)

In [42]:
s1 = pd.Series([4,5,6,87,3,6,89,4,2])
s1

0     4
1     5
2     6
3    87
4     3
5     6
6    89
7     4
8     2
dtype: int64

In [43]:
s1[0]

4

In [44]:
s1[:3]

0    4
1    5
2    6
dtype: int64

In [186]:
s1.value_counts()

4     2
6     2
2     1
3     1
5     1
87    1
89    1
dtype: int64

In [187]:
s1.unique()

array([ 4,  5,  6, 87,  3, 89,  2], dtype=int64)

In [188]:
s1.nunique()

7

In [45]:
s2 = pd.Series({'a':3,'b':[4,5,6],'c':30})
s2

a            3
b    [4, 5, 6]
c           30
dtype: object

In [46]:
s2['a']

3

In [47]:
s2[0]

3

In [48]:
s1.dtype

dtype('int64')

In [49]:
s1.size

9

In [50]:
s1.head()

0     4
1     5
2     6
3    87
4     3
dtype: int64

In [51]:
s1.tail()

4     3
5     6
6    89
7     4
8     2
dtype: int64

In [52]:
s1.sample(3)

4    3
8    2
7    4
dtype: int64

In [53]:
# Accesing s1[0]
# Inserting s1[9] = 30
# Assignment s1[0] = 31
# Deletion del s1[3]

In [54]:
df = pd.DataFrame([4,5,6,7,3,4,5,6,7,8,3])
df

0
0   4
1   5
2   6
3   7
4   3
5   4
6   5
7   6
8   7
9   8
10  3

In [55]:
pd.DataFrame([4,5,6],index=['a','b','c'],columns=['Data'])

Data
a     4
b     5
c     6

In [56]:
pd.Series([4,5,6],index=['a','b','c'],name='Data')

a    4
b    5
c    6
Name: Data, dtype: int64

In [59]:
df = pd.DataFrame([[4,'go',30.5],[11,'wow',13.3],[87,'nice',40.1]],columns=['Count','Msg','Val'])
df

Count   Msg   Val
0      4    go  30.5
1     11   wow  13.3
2     87  nice  40.1

In [58]:
pd.Series([[4,'go',30.5],[11,'wow',13.3],[87,'nice',40.1]])

0       [4, go, 30.5]
1     [11, wow, 13.3]
2    [87, nice, 40.1]
dtype: object

In [60]:
# Accessing column data
df['Count']

0     4
1    11
2    87
Name: Count, dtype: int64

In [62]:
type(df)

pandas.core.frame.DataFrame

In [63]:
type(df['Count'])

pandas.core.series.Series

In [64]:
type(df[['Count','Val']])

pandas.core.frame.DataFrame

In [61]:
# Accessing Multi-column
df[['Count','Val']]

Count   Val
0      4  30.5
1     11  13.3
2     87  40.1

In [65]:
df[['Count']]

Count
0      4
1     11
2     87

In [66]:
del df['Val']

In [67]:
df

Count   Msg
0      4    go
1     11   wow
2     87  nice

In [68]:
# Accessing the Rows in DataFrame
df.loc[1]

Count     11
Msg      wow
Name: 1, dtype: object

In [69]:
df.head(2)

Count  Msg
0      4   go
1     11  wow

In [70]:
df.values

array([[4, 'go'],
       [11, 'wow'],
       [87, 'nice']], dtype=object)

In [71]:
s1

0     4
1     5
2     6
3    87
4     3
5     6
6    89
7     4
8     2
dtype: int64

In [72]:
s1.values

array([ 4,  5,  6, 87,  3,  6, 89,  4,  2], dtype=int64)

In [ ]:
# File Handling

In [76]:
data = np.loadtxt('supermarkets.csv',delimiter=',',dtype=str)
data

array([['ID', 'Address', 'City', 'State', 'Country', 'Name', 'Employees'],
       ['1', '3666 21st St', 'San Francisco', 'CA 94114', 'USA',
        'Madeira', '8'],
       ['2', '735 Dolores St', 'San Francisco', 'CA 94119', 'USA',
        'Bready Shop', '15'],
       ['3', '332 Hill St', 'San Francisco', 'California 94114', 'USA',
        'Super River', '25'],
       ['4', '3995 23rd St', 'San Francisco', 'CA 94114', 'USA',
        "Ben's Shop", '10'],
       ['5', '1056 Sanchez St', 'San Francisco', 'California', 'USA',
        'Sanchez', '12'],
       ['6', '551 Alvarado St', 'San Francisco', 'CA 94114', 'USA',
        'Richvalley', '20']], dtype='<U16')

In [90]:
df = pd.read_csv('supermarkets.csv', index_col = 0)
df

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [78]:
pd.read_json('supermarkets.json')

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [79]:
pd.read_excel('supermarkets.xlsx')

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [80]:
pd.read_csv('supermarkets-commas.txt')

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [82]:
pd.read_csv('supermarkets-semi-colons.txt',sep=';')

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [84]:
cols = 'ID Address City State Country Name Employees'.split()
pd.read_csv('supermarkets-commas-nohead.txt',names=cols)

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [88]:
cols = 'Address City State Country Name Employees'.split()
pd.read_csv('supermarkets-commas-nohead.txt',names=cols, index_col = 0)

Address           City             State Country         Name  \
1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3      332 Hill St  San Francisco  California 94114     USA  Super River   
4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
1          8  
2         15  
3         25  
4         10  
5         12  
6         20

In [89]:
df1 = pd.read_clipboard()
df1

ID          Address           City             State Country         Name
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop
2   3      332 Hill St  San Francisco  California 94114     USA  Super River
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley

In [73]:
# Logical Indexing

In [91]:
df

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [92]:
df['Employees']>=20

ID
1    False
2    False
3     True
4    False
5    False
6     True
Name: Employees, dtype: bool

In [93]:
df[df['Employees']>=20]

Address           City             State Country         Name  \
ID                                                                          
3       332 Hill St  San Francisco  California 94114     USA  Super River   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
3          25  
6          20

In [99]:
df['Turnover'] = pd.Series([2000000,3000000,2500000,2000000,1000000,20000000],index=range(1,7))

In [100]:
df

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  Turnover  
ID                       
1           8   2000000  
2          15   3000000  
3          25   2500000  
4          10   2000000  
5          12   1000000  
6          20  20000000

In [101]:
df[(df['Employees']<20) & (df['Turnover']>2500000)]

Address           City     State Country         Name  Employees  \
ID                                                                            
2   735 Dolores St  San Francisco  CA 94119     USA  Bready Shop         15   

    Turnover  
ID            
2    3000000

In [102]:
df['Turnover'][df['Employees']>=20].mean()

11250000.0

# Pandas Functionalities

### 1. Attributes

In [104]:
s1.dtype

dtype('int64')

In [105]:
s1.empty

False

In [106]:
s1.ndim

1

In [107]:
df.ndim

2

In [108]:
df.size

42

In [109]:
s1.size

9

In [110]:
s1.values

array([ 4,  5,  6, 87,  3,  6, 89,  4,  2], dtype=int64)

In [111]:
df.values

array([['3666 21st St', 'San Francisco', 'CA 94114', 'USA', 'Madeira', 8,
        2000000],
       ['735 Dolores St', 'San Francisco', 'CA 94119', 'USA',
        'Bready Shop', 15, 3000000],
       ['332 Hill St', 'San Francisco', 'California 94114', 'USA',
        'Super River', 25, 2500000],
       ['3995 23rd St', 'San Francisco', 'CA 94114', 'USA', "Ben's Shop",
        10, 2000000],
       ['1056 Sanchez St', 'San Francisco', 'California', 'USA',
        'Sanchez', 12, 1000000],
       ['551 Alvarado St', 'San Francisco', 'CA 94114', 'USA',
        'Richvalley', 20, 20000000]], dtype=object)

In [112]:
df.T

ID                     1               2                 3              4  \
Address     3666 21st St  735 Dolores St       332 Hill St   3995 23rd St   
City       San Francisco   San Francisco     San Francisco  San Francisco   
State           CA 94114        CA 94119  California 94114       CA 94114   
Country              USA             USA               USA            USA   
Name             Madeira     Bready Shop       Super River     Ben's Shop   
Employees              8              15                25             10   
Turnover         2000000         3000000           2500000        2000000   

ID                       5                6  
Address    1056 Sanchez St  551 Alvarado St  
City         San Francisco    San Francisco  
State           California         CA 94114  
Country                USA              USA  
Name               Sanchez       Richvalley  
Employees               12               20  
Turnover           1000000         20000000

In [115]:
df

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  Turnover  
ID                       
1           8   2000000  
2          15   3000000  
3          25   2500000  
4          10   2000000  
5          12   1000000  
6          20  20000000

In [113]:
df.axes

[Int64Index([1, 2, 3, 4, 5, 6], dtype='int64', name='ID'),
 Index(['Address', 'City', 'State', 'Country', 'Name', 'Employees', 'Turnover'], dtype='object')]

In [116]:
df.index

Int64Index([1, 2, 3, 4, 5, 6], dtype='int64', name='ID')

In [117]:
df.columns

Index(['Address', 'City', 'State', 'Country', 'Name', 'Employees', 'Turnover'], dtype='object')

In [118]:
df.columns[:-1]

Index(['Address', 'City', 'State', 'Country', 'Name', 'Employees'], dtype='object')

#### 2. Statistical Views

In [119]:
s1.sum()

206

In [120]:
s1.mean()

22.88888888888889

In [122]:
s1.max()

89

In [121]:
s1.idxmax()

6

In [123]:
df.sum()

Address      3666 21st St735 Dolores St332 Hill St3995 23rd...
City         San FranciscoSan FranciscoSan FranciscoSan Fra...
State        CA 94114CA 94119California 94114CA 94114Califo...
Country                                     USAUSAUSAUSAUSAUSA
Name         MadeiraBready ShopSuper RiverBen's ShopSanchez...
Employees                                                   90
Turnover                                              30500000
dtype: object

In [125]:
df[['Employees','Turnover']].mean()

Employees    1.500000e+01
Turnover     5.083333e+06
dtype: float64

In [126]:
df.std()

Employees    6.449806e+00
Turnover     7.337688e+06
dtype: float64

In [127]:
df.min()

Address      1056 Sanchez St
City           San Francisco
State               CA 94114
Country                  USA
Name              Ben's Shop
Employees                  8
Turnover             1000000
dtype: object

In [128]:
dd = df[['Employees','Turnover']]
dd

Employees  Turnover
ID                     
1           8   2000000
2          15   3000000
3          25   2500000
4          10   2000000
5          12   1000000
6          20  20000000

In [130]:
dd.sum(axis=1)

ID
1     2000008
2     3000015
3     2500025
4     2000010
5     1000012
6    20000020
dtype: int64

In [131]:
dd.count()

Employees    6
Turnover     6
dtype: int64

In [183]:
df.sort_values('Turnover')

Address           City             State Country         Name  \
ID                                                                          
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  Turnover initials inits  logi  
ID                                            
5          12   1000000        S     S    10  
1           8   2000000        M     M    10  
4          10   2000000       BS    BS    10  
3          25   2500000       SR    SR    10  
2          15   3000000       BS    BS    25  
6          20  20000000        R     R    10

In [184]:
df.sort_index()

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  Turnover initials inits  logi  
ID                                            
1           8   2000000        M     M    10  
2          15   3000000       BS    BS    25  
3          25   2500000       SR    SR    10  
4          10   2000000       BS    BS    10  
5          12   1000000        S     S    10  
6          20  20000000        R     R    10

In [132]:
df[df['Employees']>=20].count()

Address      2
City         2
State        2
Country      2
Name         2
Employees    2
Turnover     2
dtype: int64

In [133]:
sum(df['Employees']>=20)

2

In [135]:
df

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  Turnover  
ID                       
1           8   2000000  
2          15   3000000  
3          25   2500000  
4          10   2000000  
5          12   1000000  
6          20  20000000

In [134]:
df.describe()

Employees      Turnover
count   6.000000  6.000000e+00
mean   15.000000  5.083333e+06
std     6.449806  7.337688e+06
min     8.000000  1.000000e+06
25%    10.500000  2.000000e+06
50%    13.500000  2.250000e+06
75%    18.750000  2.875000e+06
max    25.000000  2.000000e+07

In [137]:
df[df.columns[:-2]].describe()

Address           City     State Country     Name
count                6              6         6       6        6
unique               6              1         4       1        6
top     735 Dolores St  San Francisco  CA 94114     USA  Sanchez
freq                 1              6         3       6        1

In [140]:
d = df.describe(include='all')
d

Address           City     State Country     Name  Employees  \
count                6              6         6       6        6   6.000000   
unique               6              1         4       1        6        NaN   
top     735 Dolores St  San Francisco  CA 94114     USA  Sanchez        NaN   
freq                 1              6         3       6        1        NaN   
mean               NaN            NaN       NaN     NaN      NaN  15.000000   
std                NaN            NaN       NaN     NaN      NaN   6.449806   
min                NaN            NaN       NaN     NaN      NaN   8.000000   
25%                NaN            NaN       NaN     NaN      NaN  10.500000   
50%                NaN            NaN       NaN     NaN      NaN  13.500000   
75%                NaN            NaN       NaN     NaN      NaN  18.750000   
max                NaN            NaN       NaN     NaN      NaN  25.000000   

            Turnover  
count   6.000000e+00  
unique           NaN  
top              NaN  
freq             NaN  
mean    5.083333e+06  
std     7.337688e+06  
min     1.000000e+06  
25%     2.000000e+06  
50%     2.250000e+06  
75%     2.875000e+06  
max     2.000000e+07

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 1 to 6
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Address    6 non-null      object
 1   City       6 non-null      object
 2   State      6 non-null      object
 3   Country    6 non-null      object
 4   Name       6 non-null      object
 5   Employees  6 non-null      int64 
 6   Turnover   6 non-null      int64 
dtypes: int64(2), object(5)
memory usage: 556.0+ bytes


In [141]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, count to max
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Address    4 non-null      object 
 1   City       4 non-null      object 
 2   State      4 non-null      object 
 3   Country    4 non-null      object 
 4   Name       4 non-null      object 
 5   Employees  8 non-null      float64
 6   Turnover   8 non-null      float64
dtypes: float64(2), object(5)
memory usage: 704.0+ bytes


#### <b style='color:red;'>3. Working on String Data</b>

In [143]:
state = df['State']
state

ID
1            CA 94114
2            CA 94119
3    California 94114
4            CA 94114
5          California
6            CA 94114
Name: State, dtype: object

In [144]:
state.str.lower()

ID
1            ca 94114
2            ca 94119
3    california 94114
4            ca 94114
5          california
6            ca 94114
Name: State, dtype: object

In [145]:
state.str.upper()

ID
1            CA 94114
2            CA 94119
3    CALIFORNIA 94114
4            CA 94114
5          CALIFORNIA
6            CA 94114
Name: State, dtype: object

In [146]:
state.str.capitalize()

ID
1            Ca 94114
2            Ca 94119
3    California 94114
4            Ca 94114
5          California
6            Ca 94114
Name: State, dtype: object

In [147]:
state.str.len()

ID
1     8
2     8
3    16
4     8
5    10
6     8
Name: State, dtype: int64

In [148]:
len(state)

6

In [149]:
state.str.split()

ID
1            [CA, 94114]
2            [CA, 94119]
3    [California, 94114]
4            [CA, 94114]
5           [California]
6            [CA, 94114]
Name: State, dtype: object

In [151]:
state.str.cat(sep='$$')

'CA 94114$$CA 94119$$California 94114$$CA 94114$$California$$CA 94114'

In [152]:
state.str.contains('CA')

ID
1     True
2     True
3    False
4     True
5    False
6     True
Name: State, dtype: bool

In [155]:
'CA ' in df['State']

False

In [156]:
# replace
# repeat
# count
# find
# startswith
# isupper
# isnumeric
#....

#### 4. Applying Functions on Data

In [158]:
df

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  Turnover  
ID                       
1           8   2000000  
2          15   3000000  
3          25   2500000  
4          10   2000000  
5          12   1000000  
6          20  20000000

In [173]:
x = ['San','Francisco']
x

['San', 'Francisco']

In [167]:
''.join([i[0] for i in x])

'SF'

In [172]:
# Create a new column that should have initials of shop name

df['initials'] = pd.Series(map(lambda x: ''.join([i[0] for i in x]),df['Name'].str.split(' ')), index=range(1,7))
df

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  Turnover initials  
ID                                
1           8   2000000        M  
2          15   3000000       BS  
3          25   2500000       SR  
4          10   2000000       BS  
5          12   1000000        S  
6          20  20000000        R

In [174]:
df['inits'] = df['Name'].apply(lambda x:''.join([i[0] for i in x.split()]))
df

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  Turnover initials inits  
ID                                      
1           8   2000000        M     M  
2          15   3000000       BS    BS  
3          25   2500000       SR    SR  
4          10   2000000       BS    BS  
5          12   1000000        S     S  
6          20  20000000        R     R

In [175]:
df['Address'].str.len()

ID
1    12
2    14
3    11
4    12
5    15
6    15
Name: Address, dtype: int64

In [176]:
df['Name'].str.len()

ID
1     7
2    11
3    11
4    10
5     7
6    10
Name: Name, dtype: int64

In [177]:
#length_addres > 12, length_name>10 then create new column with length_addres+length_name, otherwise have the value 10 into it

In [179]:
def func(p):
    a = p['Address']
    n = p['Name']
    if len(a)>12 and len(n)>10:
        return len(a)+len(n)
    else:
        return 10

In [181]:
df['logi'] = df[['Address','Name']].apply(func,axis=1,)
df

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  Turnover initials inits  logi  
ID                                            
1           8   2000000        M     M    10  
2          15   3000000       BS    BS    25  
3          25   2500000       SR    SR    10  
4          10   2000000       BS    BS    10  
5          12   1000000        S     S    10  
6          20  20000000        R     R    10

In [185]:
#Machine Learning - Recommender System